### ISSUE TITLE
Collectable amount issue

### ISSUE THREAD

**Issue by dperfectstorm** [pathao-eng/courier-woocommerce-plugin#10]
Thank you very much for this helpful plugin. It is greatly appreciated.

After updating from Version 1.0.0 to 1.0.4, I noticed an issue with the Collectable Amount. On some of my orders, the collectable amount shows as "0".

Additionally, I have a question: Since I only have one store, is it possible to set it as the default so that I don't have to select it every time? Also, could the weight be set to 0.5 by default?

**Comment by sagar290** [comment]
Hi @dperfectstorm 

We are using [$order->get_total()](https://github.com/pathao-eng/courier-woocommerce-plugin/blob/93e1ca7b5bef8e7a5a081d58885bc4e8875e10df/plugin-api.php#L128) for collectable amount. 

This function will return 0 if the user already paid the amount. Could you please verify if there is any possibility of a third-party plugin causing this function to return 0 when the user has already paid the amount?

**Comment by sagar290** [comment]
> Also, could the weight be set to 0.5 by default?
This issue will be solved by the next release.

**Comment by dperfectstorm** [comment]
> Hi @dperfectstorm
> 
> We are using [$order->get_total()](https://github.com/pathao-eng/courier-woocommerce-plugin/blob/93e1ca7b5bef8e7a5a081d58885bc4e8875e10df/plugin-api.php#L128) for collectable amount.
> 
> This function will return 0 if the user already paid the amount. Could you please verify if there is any possibility of a third-party plugin causing this function to return 0?

When I create an order on WooCommerce, the collectable amount for that order becomes '0.' The customer has not paid, and I selected Cash on Delivery.

**Comment by dperfectstorm** [comment]
Also, the parcel status does not update. I have set up the Webhook and Webhook Secret.  https://prnt.sc/46pSO4S1zzCs

**Comment by sagar290** [comment]
I am sorry @dperfectstorm, couldn't reproduce the issue.

If you have any questions or need help, please contact us at
Email: [support@pathao.com](mailto:support@pathao.com)
Phone: +8809610003030 

Also please share your WooCommerce and WordPress versions.
