### ISSUE TITLE
Missing Special Instruction Box 

### ISSUE THREAD

**Issue by rfraihan** [pathao-eng/courier-woocommerce-plugin#23]
এখানে Special Instruction বক্সটাও অ্যাড করে দিন, এটা খুব জরুরি, এটা অপশনাল থাকবে।

**Comment by sagar290** [comment]
Hi @rfraihan 
This is fixed now. You can find these changes from this release [V1.1.5](https://github.com/pathao-eng/courier-woocommerce-plugin/releases/tag/1.1.5)
