### ISSUE TITLE
 Missing Secondary Phone

### ISSUE THREAD

**Issue by rfraihan** [pathao-eng/courier-woocommerce-plugin#27]
সেকেন্ডারি ফোন নাম্বার অ্যাড করার জন্য একটা অপশনাল ফিল্ড অ্যাড করে দিন (যাতে কারো যদি সেকেন্ডারি ফোন নাম্বার থাকে সেটা ম্যানুয়ালি অ্যাড করে দেয়া যায়), এখন দেখা যায় সেকেন্ডারি ফোন নাম্বার অ্যাড করার জন্য ম্যানুয়ালি পাঠাও প্যানেলে গিয়ে আপডেট করতে হয়।

**Comment by sagar290** [comment]
Hi @rfraihan 
You can find these changes from this release [V1.1.6](https://github.com/pathao-eng/courier-woocommerce-plugin/releases/tag/1.1.6)
