### ISSUE TITLE
Issue with Realtime status

### ISSUE THREAD

**Issue by rfraihan** [pathao-eng/courier-woocommerce-plugin#28]
আপনারা স্ক্রিনশটে যেমনটা দেখিয়েছেন, উকমার্সের ড্যাশবোর্ডে রিয়েলটাইম অর্ডার স্ট্যাটাস শো করার ব্যাপারে, আমার রিয়েলটাইম স্ট্যাটাস শো করছে না কেন?
কোন জায়গায় এডিট করে লাগবে বিস্তারিত জানাবেন প্লিজ।

পাঠাও প্যানেলে এবং আমার সাইটে Webhook Integration কিভাবে কনফিগার করবো? Callback URL এবং Secret কী কোথা থেকে পাবো বা কোন অপশনে গিয়ে জেনারেট করবো বুঝিয়ে দিন প্লিজ।
আমারটা ওয়ার্ডপ্রেস দিয়ে তৈরি

**Comment by sagar290** [comment]
If you have any questions or need help, please get in touch with us at
Email: [support@pathao.com](mailto:support@pathao.com)
Phone: +8809610003030 

Also please share your WooCommerce and WordPress versions.

**Comment by alen8694** [comment]
Apnar problem ti solve hoyeche?
